package kr.co.bullets.didemoreview

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import javax.inject.Inject

class MainActivity : AppCompatActivity() {

    // We can use @Inject annotation to tell dagger, or to give permission to dagger to use a constructor to make an object of that class.
    // If it is required to inject the object as a dependency.
    // if an inject annotated constructor has other dependencies as parameters, dagger will look for the ways to inject them as well.
//    private lateinit var smartPhone: SmartPhone

    // let’s annotate this smart phone instance variable with @Inject annotation.
    // Then, we can invoke the makeACallWithRecording() function of the smartphone.
    @Inject
    lateinit var smartPhone: SmartPhone

    // Instead we can get those dependencies to the MainActivity using field injection.
    // All we need to do this. Just delclare an instance variable and annotate it with @Inject annotation.
    // dagger will provide the memory card dependency. This approach is very easy and very efficient.
    // With the support of dagger we can get all the dependencies we want using field injection.
//    @Inject
//    lateinit var memoryCard: MemoryCard

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        // First of all we need to rebuild the project. Because dagger has not generated codes yet.
        // By rebuilding the project we can get them generated by dagger.
//        DaggerSmartPhoneComponent.create()
            // In our demo project, to get the SmartPhone dependency, we have invoked this getSmartPhone function of the smartPhoneComponent interface form the MainActivity,
            // But this is not the best and most efficient way of doing it.
            // There can be many activities and fragments in a project. And there can be many dependencies.
            // Think, If you have 10 required dependencies like this SmartPhone dependency, you may have to write getter methods for all of them in the component interface.
            // And you will have to call to them form all activities in this way.
            // This will become more difficult if you have to pass values to those dependencies at runtime.
            // Dagger library doesn’t expect us to write getter methods for dependencies like this.
            // We can just get them injected to the activities or fragments easily using field injection.
//            .getSmartPhone()
//            .makeACallWithRecording()

//        DaggerSmartPhoneComponent.create()
//            .inject(this)
//        smartPhone.makeACallWithRecording()

//        DaggerSmartPhoneComponent.builder()
//            .memoryCardModule(MemoryCardModule(1000))
//            .build()
//            .inject(this)

//        smartPhone.makeACallWithRecording()

        (application as SmartPhoneApplication).smartPhoneComponent.inject(this)
        smartPhone.makeACallWithRecording()

//        val battery = Battery()
//        val memoryCard = MemoryCard()
//        val serviceProvider = ServiceProvider()
//        val simCard = SIMCard(serviceProvider)
        // This type of dependency injection is called Constructor injection.
//        val smartPhone = SmartPhone(battery, simCard, memoryCard)
//        smartPhone.makeACallWithRecording()

//        val smartPhone = SmartPhone(
//            Battery(),
//            SIMCard(ServiceProvider()),
//            MemoryCard()
//        )
//            .makeACallWithRecording()
    }
}